@baseUrl = http://localhost:3333

POST http://localhost:3333/storages
Content-Type: application/json

{
  "name": "Almoxarifado DGI",
  "location": "Atrás do CVT Quintino",
  "details": "Pegar a chave no claviculário da DGI"
}

###
POST http://localhost:3333/storages/1/places
Content-Type: application/json

{
  "name": "Ante sala de Equipamentos",
  "location": "Segundo andar",
  "details": ""
}

###
POST http://localhost:3333/places/286f5844-bbd3-4b25-b5e8-a2f802990df0/materials
Content-Type: application/json

{
  "name": "Cabo VGA",
  "type": "Cabos",
  "model": "VGA",
  "brand": "Generico",
  "status": "nenhum",
  "quantity": 15,
  "details": ""
}

###
POST http://localhost:3333/places/286f5844-bbd3-4b25-b5e8-a2f802990df0/equipments
Content-Type: application/json

{
  "name": "Computador Core i5 4Gb 500gb",
  "type": "Desktop",
  "model": "POS14223",
  "brand": "Positivo",
  "serial": "654321",
  "status": "Não verificado",
  "patrimony": 55521544,  
  "details": "Gabinete amassado"
}

###
POST http://localhost:3333/movements
Content-Type: application/json

{  
  "type": "Entrada",
  "origin": "ETE República",
  "destiny": "Almoxarifado DGI",
  "responsible": "Rafael Petersen",
  "contact": "(21) 99858-7788",
  "equipments": [
    {
    "id": "2ce9e98d-006d-4760-96a6-84d95b30d8ca",
    "name": "Computador Core i5 4Gb 500gb",
    "type": "Desktop",
    "model": "POS14223",
    "brand": "Positivo",
    "serial": "12345678",
    "status": "Não verificado",
    "patrimony": 55521544,
    "contract": null,
    "details": "Gabinete amassado"
    },{
      "id": "bbf9649e-4158-431f-a98c-c63f0b5a0c6c",
    "name": "Computador Core i5 4Gb 500gb",
    "type": "Desktop",
    "model": "POS14223",
    "brand": "Positivo",
    "serial": "12345678",
    "status": "Não verificado",
    "patrimony": 55521544,
    "contract": null,
    "details": "Gabinete amassado"
    }
    ]
}

###
GET {{baseUrl}}/storages/1

###
GET http://localhost:3333/places/ba81361b-a8af-4492-aaf5-9c5385cbeeff

###
GET http://localhost:3333/materials

###
GET http://localhost:3333/materials/1

###
GET {{baseUrl}}/equipments

###
GET {{baseUrl}}/equipments?query=5552154

###
GET {{baseUrl}}/equipments/c2b95966-c066-4dba-bca7-c55d1f66e843